### ISSUE TITLE
Use an even more more user-friendly lobby code format

### ISSUE THREAD

**Issue by hypevhs** [scottysseus/rational-discourse#5]
Not case sensitive, not crypto-generated, no slashes, shorter in length. Omit lookalike characters.

**Comment by libjared** [comment]
Omit lookalike characters

**Comment by scottysseus** [comment]
Fixed by commit [f03d6bc986596446fa60aaaceec5845f12b9ee2e](https://github.com/scottysseus/rational-discourse/commit/f03d6bc986596446fa60aaaceec5845f12b9ee2e)
